computationalgeography/lue

environment/cmake/LueConfiguration.cmake

Build HPX before finding Boost filesystem ourselves

---

.github/workflows/macos.yml
document/luepy/case_study/CMakeLists.txt
environment/cmake/Lue.cmake
environment/cmake/LueConfiguration.cmake
environment/cmake/LueMacro.cmake
environment/conda/bld.bat
environment/conda/build.sh
source/data_model/python/CMakeLists.txt
source/data_model/python/test/CMakeLists.txt
source/framework/algorithm/test/CMakeLists.txt
source/framework/image_land/python/CMakeLists.txt
source/framework/image_land/python/test/CMakeLists.txt
source/framework/image_land/test/CMakeLists.txt
source/framework/io/test/CMakeLists.txt
source/framework/model/test/CMakeLists.txt
source/framework/partitioned_array/test/CMakeLists.txt
source/framework/partitioned_route/test/CMakeLists.txt
source/framework/python/CMakeLists.txt
source/framework/python/test/CMakeLists.txt
source/python/include/lue/py/configure.hpp.in
source/qa/python/CMakeLists.txt

Use FindPython instead of FindPython3

---

.github/workflows/macos.yml
.github/workflows/windows.yml
environment/cmake/LueConfiguration.cmake
source/data_model/utility/CMakeLists.txt
source/data_model/utility/include/lue/utility/command.hpp

Support fetching docopt.cpp ourselves

---

.editorconfig
source/framework/algorithm/test/CMakeLists.txt

Add .editorconfig to repository

---

source/framework/python/script/lue_calculate.py

Partition shape is not parsed correctly in `lue_calculate`

---

CMakeHPXPresets.json
document/doc/pcraster/status.rst
document/doc/reference/algorithm/clump.rst
document/doc/reference/algorithm/index.rst
document/doc/reference/index.rst
document/doc/reference/python/framework/zonal.rst
source/framework/algorithm/CMakeLists.txt
source/framework/algorithm/include/lue/framework/algorithm/clump.hpp
source/framework/algorithm/include/lue/framework/algorithm/default_policies/clump.hpp
source/framework/algorithm/include/lue/framework/algorithm/definition/clump.hpp
source/framework/algorithm/include/lue/framework/algorithm/value_policies/clump.hpp
source/framework/algorithm/src/zonal_operation/clump.cpp.in
source/framework/algorithm/test/CMakeLists.txt
source/framework/algorithm/test/clump_test.cpp
source/framework/core/include/lue/framework/core/domain_decomposition.hpp
source/framework/core/test/domain_decomposition_test.cpp
source/framework/io/src/raster.cpp
source/framework/python/CMakeLists.txt
source/framework/python/pcraster/__init__.py
source/framework/python/script/lue_calculate.py
source/framework/python/src/algorithm/zonal_operation.cpp
source/framework/python/src/algorithm/zonal_operation/clump.cpp
source/framework/python/test/algorithm/zonal_operation/clump_test.py
source/framework/python/test/pcraster/zonal_operation_test.py
source/qa/script/create_raster.py

Add `clump`

---

.github/workflows/conda.yml
environment/conda/bld.bat
environment/conda/build.sh
environment/conda/conda_build_config.yaml
environment/conda/meta.yaml
environment/conda/run_test.py

Fix failing C/I build: conda: macos-14 / arm-64

---

document/doc/pcraster/status.rst
source/framework/algorithm/CMakeLists.txt
source/framework/algorithm/include/lue/framework/algorithm/default_policies/maximum.hpp
source/framework/algorithm/include/lue/framework/algorithm/default_policies/minimum.hpp
source/framework/algorithm/include/lue/framework/algorithm/default_policies/sum.hpp
source/framework/algorithm/include/lue/framework/algorithm/definition/maximum.hpp
source/framework/algorithm/include/lue/framework/algorithm/definition/minimum.hpp
source/framework/algorithm/include/lue/framework/algorithm/definition/sum.hpp
source/framework/algorithm/include/lue/framework/algorithm/maximum.hpp
source/framework/algorithm/include/lue/framework/algorithm/minimum.hpp
source/framework/algorithm/include/lue/framework/algorithm/sum.hpp
source/framework/algorithm/include/lue/framework/algorithm/value_policies/sum.hpp
source/framework/algorithm/src/global_operation/maximum.cpp.in
source/framework/algorithm/src/global_operation/minimum.cpp.in
source/framework/algorithm/src/global_operation/sum.cpp.in
source/framework/algorithm/test/create_partitioned_array_test.cpp
source/framework/algorithm/test/fill_test.cpp
source/framework/algorithm/test/sum_test.cpp
source/framework/python/CMakeLists.txt
source/framework/python/pcraster/__init__.py
source/framework/python/src/algorithm/global_operation.cpp
source/framework/python/src/algorithm/global_operation/maximum.cpp
source/framework/python/src/algorithm/global_operation/minimum.cpp
source/framework/python/src/algorithm/global_operation/sum.cpp
source/framework/python/src/algorithm/local_operation.cpp
source/framework/python/test/algorithm/global_operation/maximum_test.py
source/framework/python/test/algorithm/global_operation/minimum_test.py
source/framework/python/test/algorithm/global_operation/sum_test.py
source/framework/python/test/pcraster/global_operation_test.py

Add global sum

---

.github/workflows/conda.yml
.github/workflows/linux.yml
.github/workflows/macos.yml
.pre-commit-config.yaml
document/doc/pcraster/status.rst
environment/cmake/LueConfiguration.cmake
source/framework/algorithm/CMakeLists.txt
source/framework/algorithm/include/lue/framework/algorithm/default_policies/negate.hpp
source/framework/algorithm/include/lue/framework/algorithm/definition/negate.hpp
source/framework/algorithm/include/lue/framework/algorithm/negate.hpp
source/framework/algorithm/include/lue/framework/algorithm/value_policies/negate.hpp
source/framework/algorithm/src/local_operation/negate.cpp.in
source/framework/algorithm/test/CMakeLists.txt
source/framework/algorithm/test/negate_test.cpp
source/framework/python/CMakeLists.txt
source/framework/python/include/lue/py/framework/algorithm/negate.hpp
source/framework/python/include/lue/py/framework/core/partitioned_array.hpp
source/framework/python/src/algorithm/local_operation.cpp
source/framework/python/src/algorithm/local_operation/negate.cpp
source/framework/python/test/core/partitioned_array_test.py

Add support for negate

---

.github/workflows/conda.yml
.github/workflows/linux-consume.yml
.github/workflows/linux.yml
.github/workflows/macos.yml
.github/workflows/windows.yml
source/framework/algorithm/include/lue/framework/algorithm/definition/focal_operation.hpp
source/framework/algorithm/include/lue/framework/algorithm/detail/accumulate.hpp
source/framework/core/include/lue/framework/core/offset.hpp

Port to GCC-14

---

source/framework/algorithm/include/lue/framework/algorithm/definition/accu3.hpp
source/framework/algorithm/include/lue/framework/algorithm/definition/accu_threshold3.hpp
source/framework/algorithm/include/lue/framework/algorithm/definition/binary_local_operation.hpp
source/framework/algorithm/include/lue/framework/algorithm/definition/decreasing_order.hpp
source/framework/algorithm/include/lue/framework/algorithm/definition/flow_accumulation.hpp
source/framework/algorithm/include/lue/framework/algorithm/definition/focal_operation.hpp
source/framework/algorithm/include/lue/framework/algorithm/definition/kinematic_wave.hpp
source/framework/algorithm/include/lue/framework/algorithm/definition/where.hpp
source/framework/algorithm/include/lue/framework/algorithm/definition/zonal_operation.hpp
source/framework/algorithm/include/lue/framework/algorithm/detail/verify_compatible.hpp
source/framework/algorithm/test/CMakeLists.txt
source/framework/algorithm/test/verify_compatible_test.cpp

Verify arrays have the same shape and shape in partitions

---

source/framework/algorithm/include/lue/framework/algorithm/definition/cell_index.hpp
source/framework/algorithm/test/cell_index_test.cpp

`lue.pcraster`'s `ycoordinate` outputs wrong values

---

document/doc/manual/quality_assurance/scalability/index.md
document/doc/manual/quality_assurance/scalability/quick_start.md
document/doc/reference/utility/lue_scalability.md
source/quality_assurance/scalability/command/scalability/core/process.py
source/quality_assurance/scalability/command/scalability/experiment/partition_shape/generate_script.py
source/quality_assurance/scalability/command/scalability/experiment/strong_scalability/generate_script.py
source/quality_assurance/scalability/command/scalability/experiment/weak_scalability/generate_script.py

Fix scalabilty documentation pages

---

source/framework/python/src/gdal/from_gdal.cpp

Fix `lue.pcraster.probe_gdal`

---

source/quality_assurance/scalability/command/scalability/experiment/partition_shape/generate_script.py
source/quality_assurance/scalability/command/scalability/experiment/strong_scalability/generate_script.py
source/quality_assurance/scalability/command/scalability/experiment/weak_scalability/generate_script.py

Fix handling of user's command arguments

---

.github/workflows/conda.yml
.github/workflows/linux.yml
.github/workflows/windows.yml
document/doc/contribute/release.md
environment/conda/conda_build_config.yaml
environment/conda/meta.yaml

Bump max Python version used in C/I to 3.13

---

source/framework/python/pcraster/__init__.py

Set north, west and cellsize for pcr.report

---

.github/workflows/linux.yml
environment/cmake/LueConfiguration.cmake

Consider using config mode in find_package GDAL

---

source/framework/python/pcraster/__init__.py

lue.pcraster; lddcreate does not accept string argument

---

environment/cmake/LueConfiguration.cmake
source/data_model/python/CMakeLists.txt
source/data_model/python/src/test/submodule.cpp

Remove dependency on span-lite

---

source/quality_assurance/scalability/command/scalability/core/process.py
source/quality_assurance/scalability/command/scalability/experiment/strong_scalability/generate_script.py
source/quality_assurance/scalability/command/scalability/experiment/weak_scalability/generate_script.py

When scaling over cores, make partition shape equal to array shape

---

document/doc/pcraster/status.md

Fix spelling of ifthen / ifthenelse and mention where

---

.github/workflows/linux-consume.yml
.github/workflows/linux.yml
document/doc/about/license.md
document/doc/manual/install/source.md
environment/cmake/LueConfiguration.cmake
environment/conda/meta.yaml
source/data_model/translate/include/lue/translate/command/export.hpp
source/data_model/translate/include/lue/translate/command/import.hpp
source/data_model/translate/include/lue/translate/translate.hpp
source/data_model/translate/source/command/export.cpp
source/data_model/translate/source/command/import.cpp
source/data_model/translate/source/main.cpp
source/data_model/translate/source/translate.cpp
source/data_model/utility/CMakeLists.txt
source/data_model/utility/include/lue/utility/application.hpp
source/data_model/utility/include/lue/utility/command.hpp
source/data_model/utility/source/application.cpp
source/data_model/utility/source/command.cpp
source/data_model/utility/source/print_message.cpp
source/data_model/validate/include/lue/validate/validate.hpp
source/data_model/validate/source/main.cpp
source/data_model/validate/source/validate.cpp
source/view/view/include/lue/view/application.hpp
source/view/view/include/lue/view/opengl_application.hpp
source/view/view/include/lue/view/vulkan_application.hpp
source/view/view/source/application.cpp
source/view/view/source/main.cpp
source/view/view/source/opengl_application.cpp
source/view/view/source/vulkan_application.cpp

Replace docopt by cxxopts

---

source/framework/python/source/algorithm/uniform-1.cpp

Add docstring to uniform

---

source/framework/core/include/lue/framework/core/domain_decomposition.hpp
source/framework/core/test/domain_decomposition_test.cpp

Use array shape as default partition shape in single thread case

---

source/framework/algorithm/include/lue/framework/algorithm/create_partitioned_array.hpp
source/framework/algorithm/test/create_partitioned_array_test.cpp
source/framework/python/source/numpy/from_numpy.cpp
source/framework/python/test/from_numpy_test.py
source/framework/python/test/to_numpy_test.py

Fix from_numpy crash

---

source/framework/io/source/gdal.cpp.in
source/framework/io/test/gdal_test.cpp
source/framework/python/source/gdal/from_gdal.cpp

Prevent to_gdal to write outside of the raster's shape

---

source/framework/python/pcraster/__init__.py

Only read tss files at first access

---

CMakeLists.txt
CMakePresets.json
source/framework/algorithm/test/create_partitioned_array_test.cpp

Add -Werror=missing-include-dirs to GCC

---

document/doc/manual/quality_assurance/scalability/game_of_life.py
source/data_model/translate/source/command/export.cpp

Reverse input/output arguments of `lue_translate`

---

document/doc/CMakeLists.txt
document/doc/quick_start/game_of_life.py
document/doc/quick_start/python.md
source/framework/doc/howto/trace.md

Add Python quickstart

---

.github/ISSUE_TEMPLATE/1_bug_report.yaml
.github/ISSUE_TEMPLATE/2_feature_request.yaml
.github/ISSUE_TEMPLATE/config.yml

Feature request and template chooser added

---

document/doc/CMakeLists.txt
document/doc/contribute/developer_certificate_of_origin.txt
document/doc/contribute/index.md

Add a contributor license agreement

---

source/framework/python/pcraster/__init__.py
source/framework/python/test/pcraster/numpy_test.py

Remove call to `lfr.wait()` in PCRaster sub-package's `numpy2pcr`

---

CMakeHPXPresets.json
document/doc/manual/quality_assurance/scalability/game_of_life.py
environment/cmake/LueConfiguration.cmake
source/quality_assurance/scalability/command/scalability/core/format.py
source/quality_assurance/scalability/command/scalability/core/hpx.py
source/quality_assurance/scalability/command/scalability/core/json.py
source/quality_assurance/scalability/command/scalability/core/math.py
source/quality_assurance/scalability/command/scalability/core/plot.py
source/quality_assurance/scalability/command/scalability/core/process.py
source/quality_assurance/scalability/command/scalability/experiment/cluster.py
source/quality_assurance/scalability/command/scalability/experiment/partition_shape/generate_script.py
source/quality_assurance/scalability/command/scalability/experiment/strong_scalability/generate_script.py
source/quality_assurance/scalability/command/scalability/experiment/weak_scalability/generate_script.py
source/quality_assurance/scalability/command/scalability/experiment/worker.py

Fix `lue_scalability` for distributed runs on eejit

---

.pre-commit-config.yaml
source/quality_assurance/scalability/command/scalability/experiment/benchmark.py
source/quality_assurance/scalability/command/scalability/experiment/cluster.py
source/quality_assurance/scalability/command/scalability/experiment/job.py
source/quality_assurance/scalability/command/scalability/experiment/partition_shape/generate_script.py
source/quality_assurance/scalability/command/scalability/experiment/strong_scalability/generate_script.py
source/quality_assurance/scalability/command/scalability/experiment/weak_scalability/generate_script.py

Make `scalability.py` reserve NUMA nodes instead of cluster nodes as much as possible

---

resample.sh
source/framework/algorithm/include/lue/framework/algorithm/default_policies/normal.hpp
source/framework/algorithm/include/lue/framework/algorithm/default_policies/uniform.hpp
source/framework/algorithm/include/lue/framework/algorithm/normal.hpp
source/framework/algorithm/include/lue/framework/algorithm/uniform.hpp
source/framework/algorithm/include/lue/framework/algorithm/value_policies/normal.hpp
source/framework/algorithm/include/lue/framework/algorithm/value_policies/uniform.hpp
source/framework/algorithm/test/normal_test.cpp
source/framework/algorithm/test/uniform_test.cpp
source/framework/python/pcraster/__init__.py
source/framework/python/source/algorithm/normal.cpp
source/framework/python/source/algorithm/uniform-1.cpp
source/framework/python/test/algorithm/global_operation/normal_test.py
source/framework/python/test/algorithm/global_operation/uniform_test.py
source/framework/python/test/pcraster/global_operation_test.py

Add normal and uniform overloads that return a scalar

---

environment/script/write_conan_profile.py
source/framework/core/include/lue/framework/core/array.hpp

Fix failing Windows C/I build

---

.github/workflows/linux.yml
.github/workflows/macos-homebrew.yml
.github/workflows/windows-conan.yml
.github/workflows/windows-conda.yml
conanfile.py
environment/script/write_conan_profile.py
source/framework/io/include/lue/framework/io/from_lue.hpp
source/framework/io/include/lue/framework/io/to_lue.hpp
source/framework/io/test/lue_test.cpp

lue_framework_io_lue unit tests fails once is a while

---

source/data_model/hl/include/lue/data_model/hl/dataset_view.hpp
source/data_model/python/source/hdf5/submodule.cpp
source/data_model/python/source/hdf5/submodule.hpp
source/data_model/python/source/hl/dataset_view.cpp
source/data_model/python/source/hl/raster_view.cpp
source/data_model/python/source/hl/submodule.cpp
source/data_model/python/source/hl/submodule.hpp
source/framework/api/python/CMakeLists.txt
source/framework/image_land/python/CMakeLists.txt
source/framework/python/CMakeLists.txt
source/framework/python/source/python_extension.cpp

Fix segmentation fault when importing LUE on macOS

---

source/framework/python/pcraster/__init__.py
source/framework/python/test/pcraster/local_operation_test.py

lue.pcraster max and min differ when testing for non_spatial_to_spatial
